.TH GURU 1 2026-09-17 "Guru Package Manager"

.SH NAME

\fBguru\fR \- simple package manager for gurus

.SH SYNOPSIS

\fBguru\fR [\fIguru-options\fR] \fIcommand\fB [\fIcommand-opts\fR]
.br
\fBguru\fR \fB--list\fR
.br
\fBguru\fR \fB--help\fR

.SH DESCRIPTION

Tool for installing software conforming to the \fBguru\fR(5) package format.

.SH OPTIONS

.SS Guru options

.TP
\fB--help\fR
Display brief help information and exit.

.TP
\fB--list\fR
Display list of recognized commands.  This may include built-in commands or
additional commands installed to the local system.

.TP
\fB--no-color\fR
Disable color output.  By default, \fBguru\fR will use ANSI escapes to format
the command output when connected to a terminal.

.TP
\fB--prefix\fR \fIDIR\fR
Set the directory prefix where the package will be installed.  Some packages
may not respect this setting for all package components.  By default, the
prefix will be \fB/usr/local\fR.

.TP
\fB--version\fR
Display version information and exit.

.SH EXIT STATUS

.TP
.B 0
Execution completed successfully.

.TP
.B 1
Command failed.  A descriptive error message should be written to STDERR.

.SH SEE ALSO
\fBguru\fR(5)